### ISSUE TITLE
Permission to steal website

### ISSUE THREAD

**Issue by ashmoran** [bitcoinhk/bitcoinhk.github.io#114]
Hi @Liongrass 

I think you met my friend and [Bitcoin Manchester](http://www.bitcoinmanchester.org.uk) co-organiser @MaxSan (it looks like he doesn't do much on GitHub) when he was in Hong Kong recently. He says you've invited us to let use your website design for our own. As you can see, it's *much* better than ours :-) Max has wanted this redesigned for months now.

I'm going to fork it and have a nose around. Anything I should know?

Best
Ash

**Comment by ashmoran** [comment]
We now have our fork up and running: http://bitcoinmanchester.org.uk

Hopefully we caught everything that needed rebranding. We've credited you on our [about](http://www.bitcoinmanchester.org.uk/about/) page!

**Comment by Liongrass** [comment]
Wow that's awesome! "Absolutely bluetiful" to use @larrysalibra's words, who's sitting next to me right now.

**Comment by ashmoran** [comment]
Hehe, I am no designer, making it all blue was about the limit of my skills! I will hopefully go back and add maybe a shade of navy or turquoise to the mix.

Plus we don't have cool background images like you guys, we need to add some. The layout stuff is ace though, we can do way more with this than our previous site! First idea is to add a section for local businesses. There aren't many, but I reckon we could add a section at the top easy enough.

Thanks again for letting us ~~steal~~borrow the new design :-)
